server:
  port: 8888
# our own configuration for the file storage
file:
  storage-dir: "filestorage/images/"
  client-dir: "/images/**"
spring:
  servlet: # this is for file upload
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


  datasource:
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/banking
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # or update
    generate-ddl: true
springdoc:
  swagger-ui:
    path: /

